wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1747517468
    t:
      1:
      - 1
      3:
      - 13
      - 16
      4: 3.8.12
      5: 0.12.11
      8:
      - 5
config:
  desc: null
  value: configs/base_loop.yaml
debug_mode:
  desc: null
  value: false
gpu:
  desc: null
  value:
    cuda: true
    n_gpu: 0
model:
  desc: null
  value:
    family: gpt2_loop
    loop_func: z=f(x+z)
    n_dims: 20
    n_embd: 256
    n_head: 8
    n_layer: 1
    n_positions: 101
    pred_type: regression
    pretrained_path: null
out_dir:
  desc: null
  value: ./results2/linear_regression_loop/0517213108-LR_loop_L1_ends{30}_T{15}-143d
training:
  desc: null
  value:
    add_inputs_embeds: false
    batch_size: 64
    curriculum:
      dims:
        end: 20
        inc: 1
        interval: 5000
        start: 5
      loops:
        end: 30
        inc: 2
        interval: 500
        start: 15
      points:
        end: 41
        inc: 2
        interval: 5000
        start: 11
    keep_every_steps: 100000
    learning_rate: 0.0001
    n_loop_window: 15
    resume_id: null
    save_every_steps: 1000
    seed: 42
    sparsity: 100
    task_name: linear_regression
    test_idx: -1
    test_size: 2560
    train_size: 25000
    train_steps: 500000
    use_ctx: false
    use_fixed_dataset: true
    weight_decay: 0.0
wandb:
  desc: null
  value:
    log_every_steps: 100
    name: LR_loop_L1_ends{30}_T{15}
    notes: ''
    project: Lets_Loop2_dev
    timestamp: 05/17/2025, 21:31:08
